DROP DATABASE IF EXISTS spore_devDB;
CREATE DATABASE spore_devDB;

DROP DATABASE IF EXISTS spore_testDB;
CREATE DATABASE spore_testDB;

DROP DATABASE IF EXISTS spore_proDB;
CREATE DATABASE spore_proDB;
